-- Run via: npm run db:patch

ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS screenshot_link TEXT;
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS job_link_normalized TEXT;
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS registered_by_worker_id BIGINT REFERENCES users(id) ON DELETE SET NULL;

UPDATE job_applications
SET registered_by_worker_id = worker_id
WHERE registered_by_worker_id IS NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS tech_stack TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS street TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS zip_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ssn_last4 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hourly_rate_range TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS salary_range TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS citizenship TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nationality TEXT;

NOTIFY pgrst, 'reload schema';
